### ISSUE TITLE
Mongoose 5 Compatibility

### ISSUE THREAD

**Issue by wottpal** [Zertz/mongoose-detective#4]
Is this package compatible with mongoose 5? I get this warning when using it with it:

```
npm WARN mongoose-detective@1.0.0 requires a peer of mongoose@^4.0.0 but none is installed. You must install peer dependencies yourself.
```

Could you update the dependencies if yes? Thank you in advance!!

**Comment by Zertz** [comment]
Done and released as 2.0.0
